import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const Helvetica = localFont({
  src: "../../public/fonts/Helvetica.ttf",
  subsets: ["latin"],
  variable: "--font-helvetica",
});

const TestEpiceneText = localFont({
  src: "../../public/fonts/TestEpiceneText-Medium.otf",
  subsets: ["latin"],
  variable: "--font-epicene",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Helvetica.variable} ${TestEpiceneText.variable} `}>
        {children}
      </body>
    </html>
  );
}
